#!/usr/bin/env python

# Unladen
# Copyright (C) 2014 Ryan Finnie
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import sys
import unladen.config
import unladen.httpd
import getopt


def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], '', ['config-dir=', 'debug'])
    except getopt.GetoptError as err:
        print str(err)
        sys.exit(1)

    config_dir = ''
    config_cl = {}
    for o, a in opts:
        if o == '--config-dir':
            config_dir = a
        elif o == '--debug':
            config_cl['debug'] = True
        else:
            assert False, "unhandled option"

    config = unladen.config.get_config(config_dir, config_cl)

    try:
        unladen.httpd.run(config)
    except KeyboardInterrupt:
        sys.exit(0)

if __name__ == '__main__':
    main()
